# Generated by Django 5.0.7 on 2024-10-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='island',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='Cuisine',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='Island',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
