# Generated by Django 5.0.7 on 2024-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_restaurants_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='Cuisine',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='Island',
            new_name='cuisine',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='Description',
            new_name='gmaps',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='Name',
            new_name='island',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
