# Generated by Django 5.0.7 on 2024-10-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='description',
            new_name='image',
        ),
    ]
