# Generated by Django 5.0.7 on 2024-10-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='contact',
            new_name='contacts',
        ),
    ]
