# Generated by Django 5.0.7 on 2024-10-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact'),
        ('main', '0010_auto_20241025_0844'),
    ]

    operations = [
    ]
