# Generated by Django 5.1.1 on 2024-10-24 12:07

import uuid
from django.db import migrations, models
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "restaurants_database.json")


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
